AIR = 0
WALL = 1
BARREL = 2
SPAWNPOINT = 3

BLOCK_NAMES = ['air', 'wall', 'barrel', 'spawnpoint']
BLOCK_VALUES = dict(zip(BLOCK_NAMES, range(len(BLOCK_NAMES))))

RED = 0
GREEN = 1
BLUE = 2
YELLOW = 3

MOVING_UP = 1
MOVING_DOWN = 0b10
MOVING_LEFT = 0b100
MOVING_RIGHT = 0b1000